### ISSUE TITLE
NO existing arguments

### ISSUE THREAD

**Issue by maozhuxiws** [zikai1/CVPR24_PointSetReg#1]
In test_demo.m file,
almost the  52th  line:
l
T_deformed_denormal=denormalize(tgt_pre_normal,T_deformed);
tgt_pt_denormal=denormalize(tgt_pre_normal,tgt_pt_normal);

And there is no usable arguments: tgt_pre_normal&tgt_pre_normal
where are the context about the arguments?

**Comment by zikai1** [comment]
Hi, 

Thank you for your question. 

**tgt_pre_normal** is the normalized parameters regarding the target point set. It emerges in Line 28 and 29 of the **test_demo.m**:

`[src_pt_normal,src_pre_normal]=data_normalize_input(src_pt);`
`[tgt_pt_normal,tgt_pre_normal]=data_normalize_input(tgt_pt);`

We first normalize both  the input point sets including **source** and **target** to a standard normal distribution for computational stability. But, after registration, we should denormalize the deformed point set for fair evaluation. 

If you have further question, pls do not hesitate to contact me.

Best,
MY

**Comment by maozhuxiws** [comment]
[自动回复]你好，您的邮件我已经收到。祝您生活愉快！

**Comment by maozhuxiws** [comment]
It really works. Thank you.
